name: 🐛 Bug Report
description: Report a bug or issue with Synaptic
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us understand and reproduce the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the troubleshooting guide
          required: true
        - label: I have tested with the latest version
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Setup Scripts
        - MCP Server Configuration
        - AI Orchestrator
        - Claude Desktop Integration
        - Documentation Website
        - GitHub Copilot Instructions
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the issue you're experiencing...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Navigate to '...'
        3. Click on '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - macOS
        - Linux (Ubuntu)
        - Linux (Other)
        - Windows 10
        - Windows 11
        - Windows WSL
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: Output of `node --version`
      placeholder: v18.17.0
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Output of `python --version`
      placeholder: Python 3.11.0
    validations:
      required: true

  - type: dropdown
    id: ai-model
    attributes:
      label: AI Model (if applicable)
      description: Which AI model were you using when the issue occurred?
      options:
        - Claude 3.5 Sonnet
        - GPT-4o
        - o1-preview
        - o1-mini
        - OpenCoder-8B
        - Other
        - Not applicable

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Relevant error messages or logs
      placeholder: Paste error messages, stack traces, or log output here...
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant configuration files (remove sensitive information)
      placeholder: |
        # claude_desktop_config.json (sanitized)
        {
          "mcpServers": {
            "perplexity": {
              "command": "uv",
              "args": ["--directory", "/path/to/mcp-server-perplexity", "run", "mcp-server-perplexity"]
            }
          }
        }
      render: json

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context, screenshots, or relevant information...

  - type: checkboxes
    id: ai-assistance
    attributes:
      label: AI-Assisted Development
      description: Were you using AI assistance when this issue occurred?
      options:
        - label: I was using GitHub Copilot
        - label: I was using Claude Desktop
        - label: I was using other AI tools
        - label: This issue is related to AI model behavior

