# AI Personality Configuration for Synaptic Development Orchestrator
# Based on empirical analysis of 4,442+ coding tasks across leading LLMs

ai_personalities:
  senior_architect:
    model: "claude-3-5-sonnet-20241022"
    display_name: "Senior Architect"
    description: "Comprehensive, verbose solutions for complex architecture"
    
    characteristics:
      verbosity: "high"          # 370K LOC for 4,442 tasks
      complexity: "high"         # High cyclomatic complexity
      documentation: "medium"    # 5.1% comment density
      security_risk: "medium"    # 59.57% BLOCKER vulnerabilities
      
    strengths:
      - "Complex system architecture"
      - "Comprehensive problem solving"
      - "High benchmark performance (95.57% HumanEval)"
      - "Enterprise-grade solutions"
      
    weaknesses:
      - "Over-engineering tendency"
      - "Excessive verbosity"
      - "Path-traversal vulnerabilities (34.04%)"
      - "Hard-coded credentials (14.18%)"
      
    best_for:
      - "enterprise_applications"
      - "complex_architecture"
      - "comprehensive_documentation"
      - "system_design"
      - "performance_critical"
      
    avoid_for:
      - "simple_scripts"
      - "rapid_prototypes"
      - "minimal_solutions"
      
    guardrails:
      - "verbosity_control"
      - "path_validation"
      - "credential_scanning"
      - "resource_management"
      
  rapid_prototyper:
    model: "gpt-4o-2024-11-20"
    display_name: "Rapid Prototyper"
    description: "Balanced approach for quick development and iteration"
    
    characteristics:
      verbosity: "medium"        # 209K LOC for 4,442 tasks
      complexity: "medium"       # Moderate complexity
      documentation: "low"       # 4.4% comment density
      security_risk: "medium"    # 62.50% BLOCKER vulnerabilities
      
    strengths:
      - "Balanced solutions"
      - "Quick problem solving"
      - "Reasonable code length"
      - "Good general performance"
      
    weaknesses:
      - "Control flow mistakes (48.15% of bugs)"
      - "Exception handling gaps"
      - "API contract violations"
      - "Hard-coded credentials (17.86%)"
      
    best_for:
      - "rapid_prototyping"
      - "mvp_development"
      - "general_development"
      - "balanced_solutions"
      - "iterative_development"
      
    avoid_for:
      - "security_critical"
      - "complex_control_flow"
      - "enterprise_architecture"
      
    guardrails:
      - "control_flow_validation"
      - "exception_handling"
      - "api_contract_checking"
      - "security_validation"
      
  efficient_generalist:
    model: "opencoder-8b-instruct"
    display_name: "Efficient Generalist"
    description: "Minimal, optimized code with focus on performance"
    
    characteristics:
      verbosity: "low"           # 120K LOC for 4,442 tasks
      complexity: "low"          # Lower complexity
      documentation: "medium"    # 9.9% comment density
      security_risk: "high"      # 64.18% BLOCKER vulnerabilities
      
    strengths:
      - "Minimal code generation"
      - "Efficient solutions"
      - "Good for optimization"
      - "Clear, concise logic"
      
    weaknesses:
      - "Dead code generation (42.74%)"
      - "Hard-coded credentials (29.85% - highest)"
      - "Security gaps"
      - "Limited complexity handling"
      
    best_for:
      - "code_optimization"
      - "refactoring"
      - "simple_scripts"
      - "performance_tuning"
      - "code_review"
      
    avoid_for:
      - "security_sensitive"
      - "complex_architecture"
      - "enterprise_applications"
      
    guardrails:
      - "dead_code_removal"
      - "security_hardening"
      - "credential_detection"
      - "completeness_validation"
      
  documentation_expert:
    model: "claude-3-5-haiku-20241022"
    display_name: "Documentation Expert"
    description: "Well-documented, stable solutions with high comment density"
    
    characteristics:
      verbosity: "medium"        # 288K LOC for 4,442 tasks
      complexity: "medium"       # Balanced complexity
      documentation: "high"      # 16.4% comment density (highest)
      security_risk: "medium"    # 56.03% BLOCKER vulnerabilities
      
    strengths:
      - "Excellent documentation habits"
      - "Stable, reliable patterns"
      - "Good balance of features"
      - "High comment density"
      
    weaknesses:
      - "Potentially outdated patterns"
      - "XML external entity issues (15.52%)"
      - "Control flow mistakes (23.62%)"
      
    best_for:
      - "documentation_heavy"
      - "stable_development"
      - "educational_code"
      - "maintenance_projects"
      - "team_collaboration"
      
    avoid_for:
      - "cutting_edge_features"
      - "performance_critical"
      - "modern_frameworks"
      
    guardrails:
      - "pattern_modernization"
      - "security_updates"
      - "xml_security"
      - "documentation_maintenance"
      
  high_risk_model:
    model: "llama-3.2-90b"
    display_name: "High-Risk Model"
    description: "Use with extreme caution - highest vulnerability rates"
    
    characteristics:
      verbosity: "medium"        # 197K LOC for 4,442 tasks
      complexity: "medium"       # Moderate complexity
      documentation: "medium"    # 7.3% comment density
      security_risk: "critical"  # 70.73% BLOCKER vulnerabilities (highest)
      
    strengths:
      - "Decent algorithmic performance"
      - "Good benchmark scores"
      - "Reasonable code length"
      
    weaknesses:
      - "Highest vulnerability rate (70.73% BLOCKER)"
      - "Hard-coded credentials (23.58%)"
      - "Poor engineering discipline"
      - "Control flow issues (31.06%)"
      
    best_for:
      - "non_critical_prototyping"
      - "educational_examples"
      - "algorithm_exploration"
      
    avoid_for:
      - "production_code"
      - "security_sensitive"
      - "enterprise_applications"
      - "public_facing_systems"
      
    guardrails:
      - "maximum_security_validation"
      - "mandatory_code_review"
      - "comprehensive_testing"
      - "security_scanning"

# Task-based model recommendations
task_recommendations:
  architecture_design:
    primary: "senior_architect"
    fallback: "balanced_predecessor"
    
  rapid_prototype:
    primary: "rapid_prototyper"
    fallback: "efficient_generalist"
    
  code_optimization:
    primary: "efficient_generalist"
    fallback: "rapid_prototyper"
    
  documentation:
    primary: "balanced_predecessor"
    fallback: "senior_architect"
    
  security_critical:
    primary: "senior_architect"
    fallback: "rapid_prototyper"
    avoid: ["high_risk_model", "efficient_generalist"]
    
  enterprise_development:
    primary: "senior_architect"
    fallback: "balanced_predecessor"
    avoid: ["efficient_generalist", "high_risk_model"]
    
  educational_content:
    primary: "balanced_predecessor"
    fallback: "senior_architect"

# Security vulnerability profiles by model
vulnerability_profiles:
  claude_sonnet_4:
    blocker_rate: 59.57
    critical_vulnerabilities:
      - path_traversal: 34.04
      - cryptography_misconfiguration: 24.82
      - hard_coded_credentials: 14.18
      - xxe_attacks: 10.64
      
  gpt_4o:
    blocker_rate: 62.50
    critical_vulnerabilities:
      - path_traversal: 33.93
      - cryptography_misconfiguration: 19.64
      - hard_coded_credentials: 17.86
      - xxe_attacks: 13.39
      
  opencoder_8b:
    blocker_rate: 64.18
    critical_vulnerabilities:
      - hard_coded_credentials: 29.85  # Highest rate
      - path_traversal: 28.36
      - cryptography_misconfiguration: 22.39
      - inadequate_io_handling: 7.46
      
  claude_3_7_sonnet:
    blocker_rate: 56.03
    critical_vulnerabilities:
      - path_traversal: 31.03
      - cryptography_misconfiguration: 23.28
      - xxe_attacks: 15.52  # Higher than others
      - hard_coded_credentials: 10.34
      
  llama_3_2_90b:
    blocker_rate: 70.73  # Highest overall
    critical_vulnerabilities:
      - path_traversal: 26.83
      - hard_coded_credentials: 23.58
      - cryptography_misconfiguration: 22.76
      - xxe_attacks: 19.51  # Highest rate

